export enum Periodes{
    
    MINERVALLES_ACOMPTE = 'MINERVALLES ACOMPTE',
    MINERVALLES_TOTALITE = 'MINERVALE TOTALITE',
    ENROLLEMENT_MI_SESSION = 'ENROLLEMENT MI-SESSION',
    ENROLLEMENT_PREMIERE_SESSION = 'ENROLLEMENT PREMIERE SESSION',
    ENROLLEMENT_DEUXIEME_SESSION = 'ENROLLEMENT DEUXIEME SESSION'
}